### ISSUE TITLE
Download the EIC Fun4All build via HTTPS archive does not work

### ISSUE THREAD

**Issue by ypczuchr** [eic/Singularity#2]
Dear developers

I've tried to download EIC Fun4All build via HTTPS but I've got an error:

> <h1>ERROR</h1>
> <h2>The requested URL could not be retrieved</h2>
> </div>
> <hr>
> 
> <div id="content">
> <p>The following error was encountered while trying to retrieve the URL: <a href="https://www.phenix.bnl.gov/WWW/publish/phnxbld/EIC/Singularity/MCEG.tar.bz2.md5">https://www.phenix.bnl.gov/WWW/publish/phnxbld/EIC/Singularity/MCEG.tar.bz2.md5</a></p>
> 
> <blockquote id="error">
> <p><b>Access Denied.</b></p>
> </blockquote>
> 
> <p>Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.</p>
> 
> <p>Your cache administrator is <a href="mailto:itdhelp@bnl.gov?subject=CacheErrorInfo%20-%20ERR_ACCESS_DENIED&amp;body=CacheHost%3A%20rev-cache6.bnl.gov%0D%0AErrPage%3A%20ERR_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Tue,%2016%20Jun%202020%2014%3A02%3A09%20GMT%0D%0A%0D%0AClientIP%3A%20149.156.9.135%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2FWWW%2Fpublish%2Fphnxbld%2FEIC%2FSingularity%2FMCEG.tar.bz2.md5%20HTTP%2F1.1%0AUser-Agent%3A%20curl%2F7.29.0%0D%0AAccept%3A%20*%2F*%0D%0ACache-Control%3A%20no-cache%0D%0AHost%3A%20www.phenix.bnl.gov%0D%0A%0D%0A%0D%0A">itdhelp@bnl.gov</a>.</p>

How can I grant access to all necessary files?

best regards,
Maciej Czuchry

**Comment by pinkenburg** [comment]
Hi Maciej,
the webserver is currently down. It is expected to come back by the end of this week. We are working on other solutions in case this takes longer than anticipated. I'll keep this issue open and will send instructions as soon as the server is back up or other means of distribution are available 
best regards
Chris

**Comment by pinkenburg** [comment]
Hi Maciej,

I haven't forgotten - it took longer than expected. We have a new URL for those files and I updated the script accordingly. You need to do a git pull to update your local copy and then it should work just like before. If there is a problem - please let me know. In case you are not aware of it - we have a support chat under BNL's mattermost:
https://chat.sdcc.bnl.gov/eic/channels/fun4all-software-support
If you don't have an sdcc account we can send you an invite. 

Chris
